### ISSUE TITLE
Feature Request: AppEvents supports external_id tracking

### ISSUE THREAD

**Issue by tanapoln** [facebook/facebook-ios-sdk#1496]
## Checklist

- [x] I've updated to the latest released version of the SDK
- [x] I've searched for existing feature requests on [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [x] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [x] I've given my issue the title: `Feature Request: [name of my feature request]`

## Goals

What do you want to achieve?
Conversion API for Web with Advanced Matching can set `external_id` to match the user with custom id. Currently, Facebook SDK for iOS is not supported for `external_id` field.

See the list of user data in the table here: https://developers.facebook.com/docs/app-events/advanced-matching#ios

## Expected Results

What do you expect to happen?

Facebook SDK for iOS should support `external_id` field

**Comment by rromanchuk** [comment]
@tanapoln ok so i'm not going crazy. I noticed this from events manager diagnostics tab for server to server conversions via marketing api.

I always assumed that this accessor https://github.com/facebook/facebook-ios-sdk/blob/master/FBSDKCoreKit/FBSDKCoreKit/AppEvents/FBSDKAppEvents.h#L454 was responsible for setting `external_id` in the payload  but it looks like this indeed not the case.

```swift
AppEvents.userID = "my-user-id
```

**Comment by Oliverccccct** [comment]
We started to support it from v9.3.0.
