### ISSUE TITLE
Subscription tracking not working

### ISSUE THREAD

**Issue by GZaccaroni** [facebook/facebook-ios-sdk#1521]
## Checklist

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [X] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [X] I've read the [Code of Conduct](https://github.com/facebook/facebook-ios-sdk/blob/master/CODE_OF_CONDUCT.md)
- [X] This issue is not security related and can safely be disclosed publicly on GitHub

## Environment

Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Xcode Version: `12.0.1`
- Swift Version: `X.X.X` (if issue is Swift related)
- Installation Platform & Verison: `[Cocoapods]` version `8.0.0`

## Goals

What do you want to achieve?
- Track subscriptions and purchase 
## Expected Results

What do you expect to happen?

## Actual Results
- Subscriptions are not logged correctly because `FBSDKGateKeeperAppEventsIfAutoLogSubs` value is `NO` (automatic tracking is enabled). On other apps its value is correct and it is`YES`. The SDK receives that settings from Facebook ( method `+ (void)processLoadRequestResponse:(id)result error:(NSError *)error`, class: `FBSDKGateKeeperManager`
