### ISSUE TITLE
## Checklist

### ISSUE THREAD

**Issue by geonsonroldan** [facebook/facebook-ios-sdk#1531]
## Checklist

- [x] I've updated to the latest released version of the SDK
- [x] I've searched for existing [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [x] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [x] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [x] This issue is not security related and can safely be disclosed publicly on GitHub

## Environment

Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Xcode Version: `11.6`
- Installation Platform & Verison: `[Manual]` version `7.1.1`
- iOS app Developed in C++ and Objective C

## Goals

What do you want to achieve?
Update the app with the latest Static FB SDK

## Expected Results

What do you expect to happen?
No compilation error

## Actual Results

What actually happened? Can you provide a stack trace?

Compilation error is observed
[See attachment for log]
[log.txt](https://github.com/facebook/facebook-ios-sdk/files/5062828/log.txt)
[errors.txt](https://github.com/facebook/facebook-ios-sdk/files/5062836/errors.txt)

## Steps to Reproduce

What are the steps necessary to reproduce this issue?

1. Replaced the old SDK framework with the new SDK (static framework)
2. Generate a build
3. Compilation error is observed

## Code Samples & Details

Is there a way to remove the swift dependencies? 
Why is it required for my app build with C++ and Obj C?

I have tried removing the swift dependencies issue but the enterprise build is crashing for iPhone/iPad with  iOS 11 and less with the following error:

Termination Description: DYLD, Library not loaded: @rpath/libswiftCore.dylib | Referenced from: /var/containers/Bundle/Application/40FD2ADF-D720-41F6-8AA8-EF4A27F2320A/Example.app/Example | Reason: no suitable image found.  Did find: | /private/var/containers/Bundle/Application/40FD2ADF-D720-41F6-8AA8-EF4A27F2320A/Example.app/Frameworks/libswiftCore.dylib: code signature invalid for '/private/var/containers/Bundle/Application/40FD2ADF-D720-41F6-8AA8-EF4A27F2320A/Example.app/Frameworks/libswiftCore.dylib'

__Originally posted by @narolkr in https://github.com/facebook/facebook-ios-sdk/issues/1468__

**Comment by joesus** [comment]
Duplicate of #1425
