### ISSUE TITLE
The email is not provided when disabling tracking with the limited login feature (although the access to it is granted)

### ISSUE THREAD

**Issue by tschob** [facebook/facebook-ios-sdk#1681]
## Checklist

- [x] I've updated to the latest released version of the SDK
- [x] I've searched for existing [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [x] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [x] I've read the [Code of Conduct](https://github.com/facebook/facebook-ios-sdk/blob/master/CODE_OF_CONDUCT.md)
- [x] This issue is not security related and can safely be disclosed publicly on GitHub

https://developers.facebook.com/support/bugs/2815204692081589/
## Environment

Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Xcode Version: `12.3`
- Swift Version: `5.3`
- Installation Platform & Verison: `[Cocoapods]` version `9.0.1`

## Goals

What do you want to achieve?
Receive the email address of the user while using the limited login.

## Expected Results

* The email should be part of the authentication token and set in the current profile

## Actual Results

* The email is not part of the authentication token and not set in the current profile
  * But the mail is provided when NOT using the limited login mode, but enabling tracking

## Steps to Reproduce

Use the attached demo project and login in with tracking enabled and disabled

## Code Samples & Details

[LimitedLogin.zip](https://github.com/facebook/facebook-ios-sdk/files/6116302/LimitedLogin.zip)

## Further links

I additionally opened a bug report for this: https://developers.facebook.com/support/bugs/2815204692081589/

**Comment by joesus** [comment]
First off, thank you very much for the detailed issue report and sample. I'm able to reproduce and we are investigating. Stay tuned!

**Comment by joesus** [comment]
We have fixed the issue. It should reach all users in the next few hours. Thank you again for bringing this to our attention.

**Comment by joesus** [comment]
The sample project is now working as intended. Closing.

**Comment by BrentMifsud** [comment]
I am running into this same issue with the latest version of the Facebook iOS SDK.

Aside from email being empty, fields such as "firstName" "lastName" are empty. But full name is is populated.

Login configuration as follows:

`LoginConfiguration(permissions: ["email", "public_profile", "user_birthday"], tracking: .limited)`

Some further information:

I am using a Facebook test user.
